In [47]:
import os
import pandas as pd
import numpy as np

In [48]:
a = os.getcwd()

In [49]:
path = a + '/data/quakedata.csv'

In [50]:
df = pd.read_csv(path)

In [51]:
df.head()

mag   latitude   longitude  depth   nst    gap      dmin   rms   
0  1.08  38.820999 -122.789665   1.65  11.0   79.0  0.010440  0.04  \
1  1.50  60.914200 -151.285900  57.40   NaN    NaN       NaN  0.37   
2  0.65  38.832333 -122.792168   1.83   9.0   79.0  0.006232  0.01   
3  1.98  19.197166 -155.466827  29.92  35.0  100.0       NaN  0.13   
4  1.05  33.019000 -117.074500  12.20   9.0  231.0  0.231000  0.34   

   horizontalError  depthError  magError  magNst  
0             0.48        1.21     0.270    11.0  
1              NaN        0.70       NaN     NaN  
2             0.40        1.15     0.080     9.0  
3             0.55        0.89     0.150     5.0  
4             5.09       31.61     0.119     9.0

In [52]:
df.describe()

mag      latitude     longitude         depth          nst   
count  11544.000000  11544.000000  11544.000000  11544.000000  8310.000000  \
mean       1.524903     41.976044   -121.109846     24.290589    22.796390   
std        1.204252     18.954389     62.752711     53.430475    21.436406   
min       -1.370000    -61.685700   -179.987900     -3.200000     2.000000   
25%        0.800000     33.653750   -154.966000      2.640000     8.000000   
50%        1.320000     39.195083   -122.899000      8.010000    17.000000   
75%        2.000000     58.260833   -116.637333     19.805000    30.000000   
max        7.600000     86.249600    179.927100    649.160000   258.000000   

               gap         dmin           rms  horizontalError    depthError   
count  8310.000000  6157.000000  11544.000000      7632.000000  11544.000000  \
mean    119.804504     0.536388      0.305527         1.530766      1.996206   
std      63.159766     1.890101      0.274331         2.881653      5.408441   
min      11.000000     0.000000      0.000000         0.080000      0.000000   
25%      69.462500     0.022150      0.100000         0.270000      0.400000   
50%     106.000000     0.064480      0.190000         0.430000      0.700000   
75%     158.000000     0.191300      0.490000         0.811007      1.400000   
max     355.000000    38.036000      1.650000        37.090000    313.600000   

          magError      magNst  
count  8280.000000  8302.00000  
mean      0.251469    16.67032  
std       0.381746    27.20788  
min       0.000000     0.00000  
25%       0.114000     5.00000  
50%       0.172000    10.00000  
75%       0.247207    18.00000  
max       5.350000   677.00000

In [53]:
df.fillna(df.mean())

mag   latitude   longitude  depth       nst         gap      dmin   
0      1.08  38.820999 -122.789665   1.65  11.00000   79.000000  0.010440  \
1      1.50  60.914200 -151.285900  57.40  22.79639  119.804504  0.536388   
2      0.65  38.832333 -122.792168   1.83   9.00000   79.000000  0.006232   
3      1.98  19.197166 -155.466827  29.92  35.00000  100.000000  0.536388   
4      1.05  33.019000 -117.074500  12.20   9.00000  231.000000  0.231000   
...     ...        ...         ...    ...       ...         ...       ...   
11539  1.54  33.984333 -117.055833  18.21  66.00000   25.000000  0.069360   
11540  2.20  51.643700 -173.817500  18.40  22.79639  119.804504  0.536388   
11541  1.83  17.955000  -66.963167   8.71   3.00000  206.000000  0.078480   
11542  1.40  61.259100 -146.868000  14.10  22.79639  119.804504  0.536388   
11543  2.20  59.543500 -152.437900  60.30  22.79639  119.804504  0.536388   

        rms  horizontalError  depthError  magError    magNst  
0      0.04         0.480000        1.21  0.270000  11.00000  
1      0.37         1.530766        0.70  0.251469  16.67032  
2      0.01         0.400000        1.15  0.080000   9.00000  
3      0.13         0.550000        0.89  0.150000   5.00000  
4      0.34         5.090000       31.61  0.119000   9.00000  
...     ...              ...         ...       ...       ...  
11539  0.14         0.130000        0.29  0.158000  35.00000  
11540  0.45         1.530766        5.20  0.251469  16.67032  
11541  0.13         2.970000        1.50  0.163970   3.00000  
11542  0.51         1.530766        0.80  0.251469  16.67032  
11543  0.58         1.530766        0.40  0.251469  16.67032  

[11544 rows x 12 columns]

In [54]:
df.isnull().sum()

mag                   0
latitude              0
longitude             0
depth                 0
nst                3234
gap                3234
dmin               5387
rms                   0
horizontalError    3912
depthError            0
magError           3264
magNst             3242
dtype: int64

In [55]:
df['nst'].fillna(df['nst'].mean(), inplace=True)

In [56]:
df.isnull().sum() 
# ,'dmin','horizontalError','magError','magNst'

mag                   0
latitude              0
longitude             0
depth                 0
nst                   0
gap                3234
dmin               5387
rms                   0
horizontalError    3912
depthError            0
magError           3264
magNst             3242
dtype: int64

In [57]:
df['gap'].fillna(df['gap'].mean(), inplace=True)

In [58]:
df['dmin'].fillna(df['dmin'].mean(), inplace=True)

In [59]:
df['horizontalError'].fillna(df['horizontalError'].mean(), inplace=True)

In [60]:
df['magNst'].fillna(df['magNst'].mean(), inplace=True)

In [61]:
df.isnull().sum()

mag                   0
latitude              0
longitude             0
depth                 0
nst                   0
gap                   0
dmin                  0
rms                   0
horizontalError       0
depthError            0
magError           3264
magNst                0
dtype: int64

In [62]:
df['magError'].fillna(df['magError'].mean() , inplace=True)

In [63]:
df

mag   latitude   longitude  depth       nst         gap      dmin   
0      1.08  38.820999 -122.789665   1.65  11.00000   79.000000  0.010440  \
1      1.50  60.914200 -151.285900  57.40  22.79639  119.804504  0.536388   
2      0.65  38.832333 -122.792168   1.83   9.00000   79.000000  0.006232   
3      1.98  19.197166 -155.466827  29.92  35.00000  100.000000  0.536388   
4      1.05  33.019000 -117.074500  12.20   9.00000  231.000000  0.231000   
...     ...        ...         ...    ...       ...         ...       ...   
11539  1.54  33.984333 -117.055833  18.21  66.00000   25.000000  0.069360   
11540  2.20  51.643700 -173.817500  18.40  22.79639  119.804504  0.536388   
11541  1.83  17.955000  -66.963167   8.71   3.00000  206.000000  0.078480   
11542  1.40  61.259100 -146.868000  14.10  22.79639  119.804504  0.536388   
11543  2.20  59.543500 -152.437900  60.30  22.79639  119.804504  0.536388   

        rms  horizontalError  depthError  magError    magNst  
0      0.04         0.480000        1.21  0.270000  11.00000  
1      0.37         1.530766        0.70  0.251469  16.67032  
2      0.01         0.400000        1.15  0.080000   9.00000  
3      0.13         0.550000        0.89  0.150000   5.00000  
4      0.34         5.090000       31.61  0.119000   9.00000  
...     ...              ...         ...       ...       ...  
11539  0.14         0.130000        0.29  0.158000  35.00000  
11540  0.45         1.530766        5.20  0.251469  16.67032  
11541  0.13         2.970000        1.50  0.163970   3.00000  
11542  0.51         1.530766        0.80  0.251469  16.67032  
11543  0.58         1.530766        0.40  0.251469  16.67032  

[11544 rows x 12 columns]

In [64]:
 y = df.iloc[:,0].values

In [65]:
y

array([1.08, 1.5 , 0.65, ..., 1.83, 1.4 , 2.2 ])

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11544 entries, 0 to 11543
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   mag              11544 non-null  float64
 1   latitude         11544 non-null  float64
 2   longitude        11544 non-null  float64
 3   depth            11544 non-null  float64
 4   nst              11544 non-null  float64
 5   gap              11544 non-null  float64
 6   dmin             11544 non-null  float64
 7   rms              11544 non-null  float64
 8   horizontalError  11544 non-null  float64
 9   depthError       11544 non-null  float64
 10  magError         11544 non-null  float64
 11  magNst           11544 non-null  float64
dtypes: float64(12)
memory usage: 1.1 MB


In [67]:
x = df.iloc[:,1:11].values

In [68]:
x

array([[ 3.88209991e+01, -1.22789665e+02,  1.65000000e+00, ...,
         4.80000000e-01,  1.21000000e+00,  2.70000000e-01],
       [ 6.09142000e+01, -1.51285900e+02,  5.74000000e+01, ...,
         1.53076560e+00,  7.00000000e-01,  2.51469369e-01],
       [ 3.88323326e+01, -1.22792168e+02,  1.83000000e+00, ...,
         4.00000000e-01,  1.15000000e+00,  8.00000000e-02],
       ...,
       [ 1.79550000e+01, -6.69631667e+01,  8.71000000e+00, ...,
         2.97000000e+00,  1.50000000e+00,  1.63969808e-01],
       [ 6.12591000e+01, -1.46868000e+02,  1.41000000e+01, ...,
         1.53076560e+00,  8.00000000e-01,  2.51469369e-01],
       [ 5.95435000e+01, -1.52437900e+02,  6.03000000e+01, ...,
         1.53076560e+00,  4.00000000e-01,  2.51469369e-01]])

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [70]:
from sklearn.preprocessing import MinMaxScaler
#Scaling & Normalising Data to prevent from biased data or to have a similar range
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [71]:
x_train

array([[0.8413286 , 0.08569006, 0.01796204, ..., 0.03919929, 0.00127551,
        0.04700362],
       [0.83317387, 0.08062539, 0.1049608 , ..., 0.03919929, 0.00223214,
        0.04700362],
       [0.80858353, 0.06857155, 0.00677872, ..., 0.00432316, 0.00271046,
        0.06337354],
       ...,
       [0.6742581 , 0.18656281, 0.00604462, ..., 0.00459335, 0.00213648,
        0.05457944],
       [0.63923443, 0.17667402, 0.02264779, ..., 0.01080789, 0.00318878,
        0.03551402],
       [0.63706584, 0.17779197, 0.02055482, ..., 0.00216158, 0.0018176 ,
        0.02841121]])

In [72]:
x_test

array([[6.64715161e-01, 5.79156865e-01, 2.06173007e-02, ...,
        1.16455012e-01, 5.84183673e-03, 3.68224299e-02],
       [6.39271935e-01, 1.76931971e-01, 2.25228391e-02, ...,
        4.59335315e-03, 1.53061224e-03, 2.13084112e-02],
       [8.09170009e-01, 6.84506790e-02, 1.28077171e-02, ...,
        3.91992866e-02, 0.00000000e+00, 4.70036204e-02],
       ...,
       [6.57315124e-01, 1.65132382e-01, 1.10739896e-02, ...,
        4.59335315e-03, 8.29081633e-04, 3.08411215e-02],
       [8.41609559e-01, 8.14575973e-02, 1.74622289e-01, ...,
        3.91992866e-02, 1.59438776e-03, 4.70036204e-02],
       [8.21062033e-01, 7.46859973e-02, 2.24916008e-03, ...,
        9.72710078e-03, 1.87500000e-02, 2.25844800e-02]])

# RandomForestRegressor

In [73]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score

In [74]:
rf_model = RandomForestRegressor(n_estimators=100,random_state=42)
rf_model.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [75]:
y_pred = rf_model.predict(x_test)

In [76]:
mse = mean_squared_error(y_test,y_pred)

In [77]:
print("Mean Squared Error:",mse)

Mean Squared Error: 0.13844724242950604


In [78]:
r2 = r2_score(y_test,y_pred)

In [79]:
print(r2)

0.9067792499305609


# Cross Validation 

In [93]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_squared_error

In [101]:
# Create a random forest regressor
rf = RandomForestRegressor(n_estimators=100,random_state=42, max_depth=5)

In [102]:
rf

RandomForestRegressor(max_depth=5, random_state=42)

In [103]:
# Train the model
rf.fit(x_train, y_train)

RandomForestRegressor(max_depth=5, random_state=42)

In [104]:
# Make predictions on the test set
y_pred = rf.predict(x_test)

In [105]:
# Calculate the mean squared error
mse = mean_squared_error(y_test, y_pred)
print('Mean squared error:', mse)

Mean squared error: 0.2566992718365058


In [125]:
# Perform cross-validation
cv_scores = cross_val_score(rf, x_train, y_train, cv=5)
print('Cross-validation scores:', cv_scores)

Cross-validation scores: [0.83343468 0.82713476 0.82106834 0.8140272  0.80392019]


In [126]:
# Print the mean cross-validation score
print('Mean cross-validation score:', np.mean(cv_scores))

Mean cross-validation score: 0.8199170339004821


In [127]:
r2 = r2_score(y_test,y_pred)

In [128]:
print("The R2 Score:",r2)

The R2 Score: 0.8271565526120007


# KNN Regressor 

In [133]:
# Importing the. libraries
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

In [134]:
# Create KNN Regressor 
knn = KNeighborsRegressor(n_neighbors=5)

In [135]:
# Fit the model to train the data
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [136]:
# Predict the values
y_pred = knn.predict(x_test)

In [137]:
y_pred

array([ 4.28 ,  0.916,  1.48 , ...,  1.074,  1.86 , -0.428])

In [139]:
# Now Evaluate the model
from sklearn.metrics import mean_squared_error,r2_score,cross_val_score
print("Mean squared error:", mean_squared_error(y_test, y_pred))

Mean squared error: 0.2030460541027205


In [142]:
r21 = r2_score(y_test,y_pred)

In [145]:
print("The R2 Score of the KNN Regressor",r21)

The R2 Score of the KNN Regressor 0.8632829001868113


In [150]:
# Perform cross-validation
cv_scores = cross_val_score(knn, x_train, y_train, cv=5)

In [151]:
print("Cross Validation Score:",cv_scores)

Cross Validation Score: [0.86371564 0.85767324 0.85964144 0.86209853 0.85302154]


In [152]:
# Mean Cross Validation Score
print("Mean Cross Validation Score:",np.mean(cv_scores))

Mean Cross Validation Score: 0.8592300800320297


# Decision Tree

In [159]:
# Applying Different Parameter in Decision-Tree-Regressor

In [160]:
from sklearn.tree import DecisionTreeRegressor

# Model 1

In [162]:
# Create Decision Tree
dtr = DecisionTreeRegressor()
# dtr_model1 = DecisionTreeRegressor(max_depth=5)
# dtr_model2 = DecisionTreeRegressor(max_depth=2)

In [164]:
# Fit the model to train the data
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [165]:
# Predict the values
y_pred = dtr.predict(x_test)

In [168]:
# Now Evaluate the model
from sklearn.metrics import r2_score

In [170]:
dtr_r2_score =  r2_score(y_test, y_pred)

In [172]:
# R2 Score 
print("R2 Score:",dtr_r2_score )

R2 Score: 0.8250122976032643


# Model 2

In [173]:
# Create Decision Tree 
dtr_model1 = DecisionTreeRegressor(max_depth=5)

In [174]:
# Fit the model to train the data
dtr_model1.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [175]:
# Predict the values
y_pred = dtr_model1.predict(x_test)

In [176]:
dtr_model1_r2_score =  r2_score(y_test, y_pred)

In [177]:
# R2 Score 
print("R2 Score Using Parameter Max Depth 5 :",dtr_model1_r2_score )

R2 Score Using Parameter Max Depth 5 : 0.8043661168869242


# Model 3

In [180]:
# Create Decision Tree 
dtr_model2 = DecisionTreeRegressor(max_depth=2)

In [181]:
# Fit the model to train the data
dtr_model2.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=2)

In [182]:
# Predict the values
y_pred = dtr_model2.predict(x_test)

In [184]:
# R2 Score 
print("R2 Score Using Parameter Max Depth 2 :", r2_score(y_test, y_pred))

R2 Score Using Parameter Max Depth 2 : 0.638344537468951


# Gradient Boost Neighbour

In [186]:
from sklearn.ensemble import GradientBoostingRegressor

In [187]:
gbr = GradientBoostingRegressor(n_estimators=100)

In [188]:
# Fit the model to train the data
gbr.fit(x_train,y_train)

GradientBoostingRegressor()

In [189]:
# Predict the values 
y_pred = gbr.predict(x_test)

In [191]:
# R2 Score 
print("Gradient Boost Regressor:", r2_score(y_test, y_pred))

Gradient Boost Regressor: 0.8789188674287236


In [195]:
from sklearn.metrics import mean_squared_error

In [196]:
# Mean Squared Error
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))

Mean Squared Error: 0.1798242226354951


# AdaBoost Algorithm

In [197]:
from sklearn.ensemble import AdaBoostRegressor

In [199]:
abr = AdaBoostRegressor(n_estimators=50, learning_rate=1.0, 
                                   loss='linear', random_state=None, base_estimator='deprecated')

In [200]:
# Fit the model to train the data
abr.fit(x_train,y_train)

AdaBoostRegressor()

In [201]:
# Predict the values
y_pred = abr.predict(x_test)

In [202]:
print("The R2 Score:",r2_score(y_test,y_pred))

The R2 Score: 0.7094441284515659


# ExtraTressRegressor

In [205]:
from sklearn.ensemble import ExtraTreesRegressor

In [206]:
# Create the model
etr = ExtraTreesRegressor(n_estimators=100)

In [207]:
# Fit the model to train the data
etr.fit(x_train,y_train)

ExtraTreesRegressor()

In [209]:
# Predict the values
y_pred = etr.predict(x_test)

In [210]:
print("The Model R2 Score:",r2_score(y_test,y_pred))

The Model R2 Score: 0.9127604456336204


# Lasso Regression

In [213]:
from sklearn.linear_model import Lasso

In [214]:
# Create the model 
lsr = Lasso(alpha=1.0)

In [215]:
# Fit the model to train the data
lsr.fit(x_train,y_train)

Lasso()

In [216]:
# Predict the value 
y_pred = lsr.predict(x_test)

In [217]:
# Evaluate the r2 Score
print("Lasso Model R2 Score:",r2_score(y_test,y_pred))

Lasso Model R2 Score: -1.4761831129028735e-05


# Ridge Regression

In [223]:
from sklearn.linear_model import Ridge

In [224]:
# Create the model 
rsr = Ridge()

In [225]:
# Fit the model to train the data
rsr.fit(x_train,y_train)

Ridge()

In [226]:
# Predict the value 
y_pred = rsr.predict(x_test)

In [227]:
# Evaluate the r2 Score
print("Lasso Model R2 Score:",r2_score(y_test,y_pred))

Lasso Model R2 Score: 0.7193468874253159


# XGBoost

In [229]:
import xgboost as xg

In [233]:
# Create the model 
xgb_r = xg.XGBRegressor(objective ='reg:squarederror',
                  n_estimators = 10, seed = 123)

In [234]:
# Fit the model to train the model
xgb_r.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=10, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [235]:
# Predict the value 
y_pred = xgb_r.predict(x_test)

In [236]:
# Evaluate the r2 Score
print("XGBoost Model R2 Score:",r2_score(y_test,y_pred))

XGBoost Model R2 Score: 0.8855577722600119


In [241]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error as MSE

In [243]:
rmse = np.sqrt(MSE(y_test, y_pred))

In [244]:
print("The Root Mean Squared Error:",rmse)

The Root Mean Squared Error: 0.41226741491499613


# SVR (Support Vector Regressor)

In [245]:
from sklearn.svm import SVR

In [246]:
from sklearn.model_selection import GridSearchCV

# Linear Model

In [249]:
# Create the model
lin_svr = SVR(kernel='linear' , C = 1000.0)

In [250]:
# Fit the model to train the data
lin_svr.fit(x_train,y_train)

SVR(C=1000.0, kernel='linear')

In [251]:
# Predict the values 
y_pred = lin_svr.predict(x_test)

In [252]:
# Evalute the value
print("The R2 Score:",r2_score(y_test,y_pred))

The R2 Score: 0.7100762016645414


# Polynomial Model

In [254]:
# Create the model
poly_model = SVR(kernel='poly',C = 1000.0 , degree = 2)

In [255]:
# Fit the model to train the data
poly_model.fit(x_train,y_train)

SVR(C=1000.0, degree=2, kernel='poly')

In [256]:
# Predict the values
y_pred = poly_model.predict(x_test)

In [257]:
# Evalute the value
print("The R2 Score:",r2_score(y_test,y_pred))

The R2 Score: 0.7734655894251778


# Radial basis function

In [258]:
# Create the model
rbf_model = SVR(kernel = 'rbf', C = 1000.0 , gamma=0.85)

In [259]:
# Fit the model to train the data
rbf_model.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.85)

In [261]:
# Predict the model
y_pred=rbf_model.predict(x_test)

In [262]:
# Evaluate the score 
print("The R2 Score:",r2_score(y_test,y_pred))

The R2 Score: 0.8429437176607488


In [263]:
# Create the model
bf_model = SVR(kernel = 'rbf', C = 1000.0 , gamma=0.85,degree=2) # Parameter added degree = 2

In [264]:
# Fit the model to train the data
bf_model.fit(x_train,y_train)

SVR(C=1000.0, degree=2, gamma=0.85)

In [265]:
# Predict the model
y_pred=bf_model.predict(x_test)

In [266]:
# Evaluate the score 
print("The R2 Score:",r2_score(y_test,y_pred))

The R2 Score: 0.8429437176607488


# SVR                                                                                                  # GridSearchCV  

In [267]:
# Define the model
model = SVR()

In [268]:
# Define the parameter grid
param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf', 'poly'], 'gamma': [0.1, 1, 10]}

In [269]:
# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)

In [ ]:
# Fit the data
grid_search.fit(x_train, y_train)

In [ ]:
# Access the results
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

print("Best Parameters: ", best_params)
print("Best Model: ", best_model)